### ISSUE TITLE
What certificates required for Windows signing?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cli-plugin-repo#172]
Re https://github.com/cloudfoundry-incubator/cli-plugin-repo/blob/master/README.md#sign-windows-binaries

How do I generate/buy/etc the certificates required for signing CLI plugins? Or can I use the CFF certs?

**Comment by dkoper** [comment]
@chipchilders Can you answer these questions?

**Comment by mogul** [comment]
(Certificates should only be used to sign binaries that the owner of the certificate is willing to vouch for... I wouldn't expect to see the CFF certs used for signing plugins unless CFF is providing the builds.)

**Comment by chipchilders** [comment]
@drnic you can't use the CFF certs for non-CFF projects

The process was pretty complex from the CLI team's side. All I helped with was the purchase (and required organizational verification process) for both an official Apple code signing cert and a Windows code signing cert. The Apple one comes from Apple (you need a developer account with them) and the Windows code signing cert came from a commercial certificate authority.

@dkoper - the CLI team should have information about how the certs are used to build and sign the CLI binary itself. LInking to that might be helpful for everyone.

**Comment by drnic** [comment]
Ok I understand not being able to borrow another orgs cert.

On the downside I still don't have any certs and am not sure where to get them from, how much it will cost to distribute free OSS plugins to windows users etc.

Can we add some docs on where to buy certs (what type etc, what they cost) etc?

________________________________

**Comment by mogul** [comment]
[This Quora article](https://www.quora.com/Where-can-I-find-free-or-cheap-code-signing-certificate) was somewhat helpful for us (though we haven't actually bought yet for cloud.gov to government obstacles).

**Comment by dkoper** [comment]
I have added a bit more detail to https://github.com/cloudfoundry-incubator/cli-plugin-repo#sign-windows-binaries. In particular, more info of the type of code signing cert to help you google it.

For the Windows certs you need to select a commercial cert provider. I don't think we can/should do that selection or recommend a particular one. Also, a price comparison, even including a rough price range in every currency that the cf CLI is available feels a bit out of scope for our team to provide..

**Comment by dkoper** [comment]
Closing. With the PR from @mogul merged I think all guidance is there.
