### ISSUE TITLE
Remove cf recycle because of major bug

### ISSUE THREAD

**Issue by eloo** [cloudfoundry/cli-plugin-repo#261]
The current version of the cf recycle plugin has a major bug which can cause downtimes. 
So its not safe to it till this issue is fixed.
As an alternative there seems to be a fork of the plugin which fixes this issue.

Maybe the comcast plugin should be removed and the fork added.

For more details see https://github.com/Comcast/cf-recycle-plugin/issues/3

thx

**Comment by abbyachau** [comment]
Hi @eloo thanks for reaching out, it looks like the administrators of the plugin made changes to update the plugin - we recommend you reach out to the plugin authors to get a update on the status of the fix. If they would like us to remove the plugin, then please have them reach out to us.

**Comment by eloo** [comment]
@abbyachau 
looks like the maintainer has fixed the issue and created a new release.
so it would be great if you could update the plugin repo
