### ISSUE TITLE
spring-cloud-services-cli-plugin 1.0.24 installation should mention 1.0.24 version (not 1.0.23)

### ISSUE THREAD

**Issue by tremblaysimon** [cloudfoundry/cli-plugin-repo#457]
Currently https://github.com/cloudfoundry/cli-plugin-repo/pull/453 updated to `1.0.24` the spring-cloud-services-cli-plugin but when we install it from the cf CLI it continues to indicate `1.0.23`. Maybe because that line wasn't updated: https://github.com/cloudfoundry/cli-plugin-repo/blame/main/repo-index.yml#L1695

**Comment by jessecoddington** [comment]
PR was just merged https://github.com/cloudfoundry/cli-plugin-repo/pull/460

**Comment by moleske** [comment]
should be updated now
