### ISSUE TITLE
feature request: add RSS/Atom feed of plugins

### ISSUE THREAD

**Issue by afeld** [cloudfoundry/cli-plugin-repo#95]
I visit https://plugins.cloudfoundry.org/ every once in a while, and am always pleasantly surprised at the new plugins I discover. Would be nice to be able to subscribe to new plugins. Thanks!

**Comment by dkoper** [comment]
Interesting idea, thanks!
We'll explore what's involved in implementing this.
BTW, we have a story scheduled to list outdated installed plugins, which wouldn't address your use case, but may bring more traffic to the site.

**Comment by heyjcollins** [comment]
Hello @afeld - 
I'm doing some cleanup and see this issue has been open for a few years.
This would be nice to have but TBH I don't see this rising to the top of our priority list.
As such I'm going to close this issue.
Please feel free to comment and reopen if you're still interested in pushing for this and of course we're always open to PR's.
